apply plugin: 'com.android.library'

android {
    compileSdkVersion 33

    namespace "com.PrimeSoftwareSystems.Sundial"

    defaultConfig {
        minSdkVersion 30
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 33
                buildToolsVersion "28.0.3"
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.0.0'
    compileOnly files('C:\\Program Files\\Unity\\Hub\\Editor\\2023.2.18f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\Variations\\il2cpp\\Release\\Classes\\classes.jar')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}

task getDeps(type: Copy) {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    if( !sourceSets.collect {it.name}.contains("main")) return 
    from (sourceSets.main.compileClasspath){
        include ("**/*.jar")
        include ("**/*.class")
    }
    from (sourceSets.main.runtimeClasspath){
    	include ("**/*.jar")
        include ("**/*.class")
    }
    from (sourceSets.test.compileClasspath){
        include ("**/*.jar")
        include ("**/*.class")
    }
    from (sourceSets.test.runtimeClasspath){
        include ("**/*.jar")
        include ("**/*.class")
    }
	into ("build/runtimeLibs/")
}